### ISSUE TITLE
Suspected: If value of a SELECT is 0 or 1, values are not parsed as integers

### ISSUE THREAD

**Issue by johanneseckert** [pklaschka/xd-dialog-helper#14]
### Description of the bug
I don't have a way to confirm this with vanilla code, but here's what I'm seeing:

### Code example
My code is iterating over a list of filenames on a directory and populating the choices into a dropdown. I'm registering the index of the files as the value of the select. When the user chooses either 0 or 1, the result is empty ` `

```javascript
{
  type: DialogHelper.SELECT,
  id: 'whichOption',
  label: 'Choose an option:',
  options: [
    {
      label: 'Option 1',
      value: 0
    },
    {
      label: 'Option 2',
      value: 1
    }
  ],
  value: 0
}
```

I don't have a quick way to confirm this with vanilla code (my plugin is too complex to pull this out at the moment). Can you confirm this?

**Version:** `0.9.3`

**Comment by johanneseckert** [comment]
when I amateurishly offset the `value` index by 5, it works reliably

**Comment by johanneseckert** [comment]
related, I have seen an empty output when the slider value is 0, but I don't know if that's maybe a parsing error on my side or just the XD console not being good in reporting

**Comment by pklaschka** [comment]
@johanneseckert I can confirm this and am pushing a fix right now. Please note, however, that values (except for those of sliders) get treated as strings, so you'll have to cast them to numbers in order for your value to work as an index.

If you encounter any further problems, please feel free to let me know.

Thank you very much for bringing this up (you're the number 1 issue reporter of this repo, thank you for that contribution 👍),
Happy Coding,
Pablo

**Comment by johanneseckert** [comment]
ha, bug in your code and a bug in my code :)
Duh, of course I need to parse it as integer when retrieving, make a lot of sense for values of dropdowns, thanks for pointing that out.
